name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'

  netsuite:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo ${{ github }}
      # - name: Dump job context
      #   run: echo ${{ toJSON(job) }}
      # - name: Dump steps context
      #   run: echo ${{ toJSON(steps) }}
      # - name: Dump runner context
      #   run: echo ${{ toJSON(runner) }}
      # - name: Dump strategy context
      #   run: echo ${{ toJSON(strategy) }}
      # - name: Dump matrix context
      #   run: echo ${{ toJSON(matrix) }}

  automerge:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: true
