name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'

  netsuite:
    runs-on: ubuntu-latest
    steps:
      - name: echo netsuite
        run: echo "Running netsuite" ${{ inputs.release }}
#   deploy app:
#     steps:
#     run: |
#       echo "deploying app"

# automerge:
#   needs: [build]
#   runs-on: ubuntu-latest
#   permissions:
#     pull-requests: write
#     contents: write
#   steps:
#     - uses: fastify/github-action-merge-dependabot@v3
