name: Add Labels

on:
  workflow_dispatch:
  pull_request:
    types: opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read|write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Actions Ecosystem Add Labels
        uses: actions-ecosystem/action-add-labels@v1.1.0

        with:
          labels: |
            documentation
