name: Add Labels

on:
  workflow_dispatch:
  pull_request:
    types: opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            documentation
