name: pull req closed

on:
  pull_request:
    types:
      - closed

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Output
        id: set-output
        run: |
          echo "::set-output name=myVariable::My Value"
